import { useState } from "react";
import { fetchPolicies } from "../services/api";
import LoadingSpinner from "../components/LoadingSpinner";
import SectorBadge from "../components/SectorBadge";
import { FileText, Sparkles, Download, ChevronRight } from "lucide-react";

const COUNTRIES = [
    "India", "Indonesia", "Nigeria", "Kenya", "Brazil", "Mexico",
    "Argentina", "Saudi Arabia", "United Arab Emirates", "South Africa",
    "South Korea", "Japan", "Australia", "Canada", "United Kingdom",
    "Germany", "France", "Singapore", "United States", "European Union"
];

const SECTORS = [
    "AI Governance", "Cybersecurity", "Data Privacy",
    "Healthcare AI", "Financial Regulation",
    "POSH Policies", "ESG Policies", "IoT and Robotics"
];

export default function GeneratePolicy() {
    const [country, setCountry] = useState("");
    const [sector, setSector] = useState("");
    const [result, setResult] = useState(null);
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState(null);

    const handleGenerate = async () => {
        if (!country || !sector) return;
        setLoading(true);
        setError(null);

        try {
            const res = await fetch("http://localhost:8000/api/generate/policy-template", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ country, sector })
            });
            const data = await res.json();
            if (!res.ok) throw new Error(data.error || "Generation failed");
            setResult(data);
        } catch (err) {
            setError(err.message);
        } finally {
            setLoading(false);
        }
    };

    const downloadTemplate = () => {
        if (!result) return;
        const content = `
POLICY TEMPLATE — GENERATED BY POLICYIQ
========================================
Country: ${result.country}
Sector: ${result.sector}
Suggested Title: ${result.suggested_title}
Generated: ${new Date().toLocaleString()}

CONTEXT
-------
${result.policy_context}

REGULATORY GAP
--------------
${result.regulatory_gap
                ? `${result.country} does NOT currently have a dedicated ${result.sector} framework.`
                : `${result.country} has existing ${result.sector} regulation that this template supplements.`
            }

MATURITY LEVEL: ${result.maturity_level.toUpperCase()}

PRIORITY AREAS
--------------
${result.priority_areas.map((p, i) => `${i + 1}. ${p}`).join('\n')}

RECOMMENDED SECTIONS
--------------------
${result.recommended_sections.join('\n')}

KEY REQUIREMENTS
----------------
${result.key_requirements.map((r, i) => `${i + 1}. ${r}`).join('\n')}

IMPLEMENTATION TIMELINE
-----------------------
${Object.entries(result.implementation_timeline)
                .map(([phase, desc]) => `${phase}:\n   ${desc}`)
                .join('\n\n')}

REFERENCE POLICIES
------------------
${result.reference_policies.map(p =>
                    `- ${p.title} (${p.country})\n  ${p.source_url}`
                ).join('\n')}

RECOMMENDED TAGS
----------------
${result.recommended_tags.join(', ')}

========================================
Generated by PolicyIQ — Global Policy Intelligence System
This template is for reference only and should be reviewed by legal experts.
    `.trim();

        const blob = new Blob([content], { type: "text/plain" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `PolicyTemplate_${result.country}_${result.sector}.txt`;
        a.click();
        URL.revokeObjectURL(url);
    };

    return (
        <div style={{ padding: "28px 32px" }}>
            {/* Header */}
            <div className="fade-up" style={{ marginBottom: 24 }}>
                <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 4 }}>
                    <div style={{ width: 3, height: 22, background: "#10b981", borderRadius: 2 }} />
                    <h1 style={{ fontFamily: "Syne", fontSize: 22, fontWeight: 800, color: "var(--text-main)" }}>
                        Policy Template Generator
                    </h1>
                    <div style={{
                        display: "flex", alignItems: "center", gap: 6, marginLeft: 8,
                        padding: "3px 10px", borderRadius: 20,
                        background: "rgba(16,185,129,0.1)",
                        border: "1px solid rgba(16,185,129,0.2)"
                    }}>
                        <Sparkles size={11} color="#10b981" />
                        <span style={{ fontSize: 11, color: "#10b981", fontFamily: "JetBrains Mono" }}>
                            AI GENERATED
                        </span>
                    </div>
                </div>
                <p style={{ color: "var(--text-muted)", fontSize: 13, paddingLeft: 13 }}>
                    Generate a policy framework template tailored to a specific country and sector
                </p>
            </div>

            {/* Input Panel */}
            <div className="card fade-up fade-up-1" style={{ padding: "24px 28px", marginBottom: 24 }}>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }}>
                    {/* Country */}
                    <div>
                        <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "JetBrains Mono", marginBottom: 8 }}>
                            SELECT COUNTRY
                        </div>
                        <select value={country} onChange={e => setCountry(e.target.value)} style={{
                            width: "100%", padding: "10px 14px", borderRadius: 8,
                            background: "var(--bg-hover)", border: "1px solid var(--border)",
                            color: "var(--text-main)", fontSize: 13, outline: "none",
                        }}>
                            <option value="">Choose a country...</option>
                            {COUNTRIES.map(c => <option key={c} value={c}>{c}</option>)}
                        </select>
                    </div>

                    {/* Sector */}
                    <div>
                        <div style={{ fontSize: 11, color: "var(--text-muted)", fontFamily: "JetBrains Mono", marginBottom: 8 }}>
                            SELECT SECTOR
                        </div>
                        <select value={sector} onChange={e => setSector(e.target.value)} style={{
                            width: "100%", padding: "10px 14px", borderRadius: 8,
                            background: "var(--bg-hover)", border: "1px solid var(--border)",
                            color: "var(--text-main)", fontSize: 13, outline: "none",
                        }}>
                            <option value="">Choose a sector...</option>
                            {SECTORS.map(s => <option key={s} value={s}>{s}</option>)}
                        </select>
                    </div>
                </div>

                {error && (
                    <div style={{
                        padding: "10px 14px", borderRadius: 8, marginBottom: 16,
                        background: "rgba(244,63,94,0.08)", border: "1px solid rgba(244,63,94,0.2)",
                        color: "#f43f5e", fontSize: 12
                    }}>
                        {error}
                    </div>
                )}

                <button onClick={handleGenerate} disabled={!country || !sector || loading} style={{
                    width: "100%", padding: "12px",
                    background: (!country || !sector || loading)
                        ? "var(--bg-hover)"
                        : "linear-gradient(135deg, #059669, #10b981)",
                    border: "none", borderRadius: 8,
                    color: (!country || !sector || loading) ? "var(--text-muted)" : "#fff",
                    fontFamily: "Syne", fontWeight: 700,
                    fontSize: 14, cursor: (!country || !sector || loading) ? "not-allowed" : "pointer",
                }}>
                    {loading ? "Generating Template..." : "Generate Policy Template"}
                </button>
            </div>

            {loading && <LoadingSpinner label="Analyzing country needs and generating template..." />}

            {/* Results */}
            {result && !loading && (
                <div className="fade-up">

                    {/* Title Banner */}
                    <div className="card" style={{
                        padding: "20px 24px", marginBottom: 16,
                        borderColor: "rgba(16,185,129,0.3)",
                        background: "rgba(16,185,129,0.05)"
                    }}>
                        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
                            <div>
                                <div style={{ fontSize: 11, color: "#10b981", fontFamily: "JetBrains Mono", marginBottom: 6 }}>
                                    GENERATED TEMPLATE
                                </div>
                                <div style={{ fontFamily: "Syne", fontWeight: 800, fontSize: 18, color: "var(--text-main)", marginBottom: 8 }}>
                                    {result.suggested_title}
                                </div>
                                <div style={{ display: "flex", gap: 12, alignItems: "center", flexWrap: "wrap" }}>
                                    <SectorBadge sector={result.sector} />
                                    <span style={{ fontSize: 12, color: "var(--text-muted)" }}>
                                        {result.country}
                                    </span>
                                    <span style={{
                                        fontSize: 11, padding: "2px 8px", borderRadius: 4,
                                        background: result.regulatory_gap
                                            ? "rgba(244,63,94,0.08)" : "rgba(16,185,129,0.08)",
                                        color: result.regulatory_gap ? "#f43f5e" : "#10b981",
                                        border: `1px solid ${result.regulatory_gap ? "rgba(244,63,94,0.2)" : "rgba(16,185,129,0.2)"}`,
                                        fontFamily: "JetBrains Mono"
                                    }}>
                                        {result.regulatory_gap ? "Gap Identified" : "Supplement Existing"}
                                    </span>
                                    <span style={{
                                        fontSize: 11, padding: "2px 8px", borderRadius: 4,
                                        background: "var(--bg-hover)", color: "var(--text-muted)",
                                        border: "1px solid var(--border)", fontFamily: "JetBrains Mono"
                                    }}>
                                        {result.maturity_level} maturity
                                    </span>
                                </div>
                            </div>
                            <button onClick={downloadTemplate} style={{
                                display: "flex", alignItems: "center", gap: 6,
                                padding: "8px 16px", borderRadius: 8,
                                background: "rgba(16,185,129,0.1)",
                                border: "1px solid rgba(16,185,129,0.3)",
                                color: "#10b981", fontSize: 12,
                                cursor: "pointer", fontFamily: "JetBrains Mono",
                                flexShrink: 0
                            }}>
                                <Download size={13} /> Download .txt
                            </button>
                        </div>
                    </div>

                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 }}>

                        {/* Recommended Sections */}
                        <div className="card" style={{ padding: "20px 24px" }}>
                            <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                                RECOMMENDED SECTIONS
                            </div>
                            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
                                {result.recommended_sections.map((s, i) => (
                                    <div key={i} style={{
                                        display: "flex", alignItems: "center", gap: 8,
                                        padding: "6px 10px", borderRadius: 6,
                                        background: "var(--bg-hover)", border: "1px solid var(--border)"
                                    }}>
                                        <ChevronRight size={12} color="var(--cyan)" />
                                        <span style={{ fontSize: 12, color: "var(--text-main)" }}>{s}</span>
                                    </div>
                                ))}
                            </div>
                        </div>

                        {/* Key Requirements + Timeline */}
                        <div style={{ display: "flex", flexDirection: "column", gap: 16 }}>
                            <div className="card" style={{ padding: "20px 24px" }}>
                                <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                                    KEY REQUIREMENTS
                                </div>
                                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                                    {result.key_requirements.map((r, i) => (
                                        <div key={i} style={{ display: "flex", gap: 8, alignItems: "flex-start" }}>
                                            <div style={{
                                                width: 18, height: 18, borderRadius: "50%",
                                                background: "rgba(16,185,129,0.15)",
                                                border: "1px solid rgba(16,185,129,0.3)",
                                                color: "#10b981", fontSize: 10,
                                                display: "flex", alignItems: "center", justifyContent: "center",
                                                flexShrink: 0, fontFamily: "JetBrains Mono"
                                            }}>
                                                {i + 1}
                                            </div>
                                            <span style={{ fontSize: 12, color: "var(--text-main)", lineHeight: 1.5 }}>{r}</span>
                                        </div>
                                    ))}
                                </div>
                            </div>

                            {/* Implementation Timeline */}
                            <div className="card" style={{ padding: "20px 24px" }}>
                                <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                                    IMPLEMENTATION TIMELINE
                                </div>
                                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                                    {Object.entries(result.implementation_timeline).map(([phase, desc], i) => (
                                        <div key={i} style={{
                                            padding: "8px 12px", borderRadius: 8,
                                            background: "var(--bg-hover)", border: "1px solid var(--border)"
                                        }}>
                                            <div style={{ fontSize: 11, color: "var(--cyan)", fontFamily: "JetBrains Mono", marginBottom: 3 }}>
                                                {phase}
                                            </div>
                                            <div style={{ fontSize: 12, color: "var(--text-muted)" }}>{desc}</div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>
                    </div>

                    {/* Priority Areas + Tags */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 16, marginBottom: 16 }}>
                        <div className="card" style={{ padding: "20px 24px" }}>
                            <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                                PRIORITY AREAS FOR {result.country.toUpperCase()}
                            </div>
                            <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
                                {result.priority_areas.map((p, i) => (
                                    <span key={i} style={{
                                        fontSize: 12, padding: "4px 12px", borderRadius: 20,
                                        background: "rgba(245,158,11,0.1)",
                                        border: "1px solid rgba(245,158,11,0.2)",
                                        color: "#f59e0b"
                                    }}>
                                        {p}
                                    </span>
                                ))}
                            </div>
                        </div>

                        <div className="card" style={{ padding: "20px 24px" }}>
                            <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                                RECOMMENDED POLICY TAGS (BY PRIORITY)
                            </div>
                            <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                                {result.recommended_tags.map((t, i) => (
                                    <span key={i} style={{
                                        fontSize: 11, padding: "3px 10px", borderRadius: 4,
                                        background: "var(--bg-hover)", color: "var(--text-muted)",
                                        border: "1px solid var(--border)", fontFamily: "JetBrains Mono"
                                    }}>
                                        #{t}
                                    </span>
                                ))}
                            </div>
                        </div>
                    </div>

                    {/* Reference Policies */}
                    <div className="card" style={{ padding: "20px 24px" }}>
                        <div style={{ fontSize: 11, color: "var(--text-dim)", fontFamily: "JetBrains Mono", marginBottom: 12 }}>
                            REFERENCE POLICIES — MODEL THESE FRAMEWORKS
                        </div>
                        <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                            {result.reference_policies.map((p, i) => (
                                <div key={i} style={{
                                    display: "flex", justifyContent: "space-between", alignItems: "center",
                                    padding: "10px 14px", borderRadius: 8,
                                    background: "var(--bg-hover)", border: "1px solid var(--border)"
                                }}>
                                    <div>
                                        <div style={{ fontSize: 13, color: "var(--text-main)", fontWeight: 600 }}>{p.title}</div>
                                        <div style={{ fontSize: 11, color: "var(--text-muted)" }}>{p.country}</div>
                                    </div>
                                    {p.source_url && (
                                        <a href={p.source_url} target="_blank" rel="noreferrer" style={{
                                            fontSize: 11, color: "var(--cyan)",
                                            textDecoration: "none", fontFamily: "JetBrains Mono",
                                            padding: "3px 8px", borderRadius: 4,
                                            border: "1px solid rgba(34,211,238,0.2)",
                                            background: "rgba(34,211,238,0.06)"
                                        }}>
                                            ↗ Source
                                        </a>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>

                </div>
            )}
        </div>
    );
}